export enum NotificationType {
  PETITION_CREATED = 'PETITION_CREATED',
  PETITION_UPDATED = 'PETITION_UPDATED',
  PETITION_DELETED = 'PETITION_DELETED',
  VOTE_ADDED = 'VOTE_ADDED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  COMMENT_REPLIED = 'COMMENT_REPLIED',
  SYSTEM = 'SYSTEM'
} 